////////////////////////////////////////////////////////////////////////////////
// Filename: Glossary.h
////////////////////////////////////////////////////////////////////////////////

#pragma once

#pragma region COMMON
#define EMPTY_CSTR						""

#pragma endregion

#pragma region RESOURCES
#define AXIS_MESH_PATH					"./Resources/Gizmo/Axis2/Axis.obj"
#define DIRECTIONAL_LIGHT_MESH_PATH		"./Resources/Gizmo/DirectionalLight/DirectionalLight.obj"
#define POINT_LIGHT_MESH_PATH			"./Resources/Gizmo/PointLight/PointLight.obj"
#define SPOT_LIGHT_MESH_PATH			"./Resources/Gizmo/SpotLight/SpotLight.obj"
#define CUBE_MESH_PATH					"./Resources/Cube2/Cube2.obj"
#define	TEXTURE_LOGO_PATH				"./Resources/Textures/Logo.png"
#define CONFIG_FILE_PATH				"./Resources/XmlConfigurationFiles/Config.xml"
#define MISSING_TEXTURE					"./Resources/Textures/normal_up.jpg"
#define DEFAULT_FONT					"./Resources/Fonts/calibri.ttf"
#define PLANE_MESH_PATH					"./Resources/Plane2/plane.obj"
#define CUBE_MESH_PATH					"./Resources/Cube2/Cube2.obj"
#define	QUAD_MESH_PATH					"./Resources/quad.obj"
#define SKYBOX_SPHERE_MESH_PATH			"./Resources/SkyBox/sphere.obj"
#pragma endregion

#pragma region SHADER_NAMES
#define SHADER_GIZMO					"Gizmo"
#define SHADER_BASE_MESH				"BaseMesh"
#define SHADER_SKINNED_MESH				"SkinnedMesh"
#define SHADER_SKYBOX					"Skybox"
#define SHADER_GEOMETRY 				"Geometry"
#define SHADER_BLUR 					"Blur"
#define SHADER_SSAO 					"SSAO"
#define SHADER_SHADOW_MAP 				"ShadowMap"
#define SHADER_SHADOW_MAP2 				"ShadowMap2"
#define SHADER_SHADOW_CUBE_MAP			"ShadowCubeMap"
#define SHADER_SHADOW_CUBE_MAP2			"ShadowCubeMap2"
#define SHADER_POST_PROCESSING			"PostProcessing"
#define SHADER_NORMAL_VIEWER			"NormalViewer"
#define SHADER_BLOOM					"Bloom"
#define SHADER_TEXT_RENDERER			"TextRenderer"
#define SHADER_LOGO						"Logo"
#define SHADER_OCCLUSION_RENDER			"OcclusionRender"
#define SHADER_SUBSTATE_MESH_INSTANCED	"SubstateMeshInstanced"
#define SHADER_SUBSTATE_MESH_FRONTFACE	"SubstateMeshVolumeFrontFace"
#define SHADER_SUBSTATE_MESH_VOLUME		"SubstateMeshVolume"
#define SHADER_SUBSTATE_MESH_SURFACE	"SubstateMeshSurface"
#define SHADER_INFOBAR_RENDERER			"InfoBarRenderer"
#pragma endregion

#pragma region SCENELOADER_NAMES
#define GRAPH_SCENE_STR					string("GraphScene") 
#define ENVIRONMENT_STR					string("Environment")
#define AMBIENT_OCCLUSION_STR			string("AmbientOcclusion")
#define KERNEL_SIZE_CSTR				"kernel"
#define SCENE_OBJECT_STR				string("SceneObject")
#define COMPONENTS_STR					string("Components")
#define TRANSFORM_COMPONENT_STR			string("Transform")
#define CAMERA_COMPONENT_STR			string("Camera")
#define MESH_COMPONENT_STR				string("Mesh")
#define LIGHT_COMPONENT_STR				string("Light")
#define BEHAVIOUR_COMPONENT_STR			string("Behaviour")
#define PHYSICS_COMPONENT_STR			string("Physics")
#define AUDIO_COMPONENT_STR				string("Audio")
#define PARTICLES_COMPONENT_STR			string("Particles")
#define ID_CSTR							"id"
#define TAG_CSTR						"tag"
#define ENABLED_CSTR					"enabled"
#define TRUE_STR						string("true")
#define FALSE_STR						string("false")
#define POSITION_STR					string("Position")
#define ROTATION_STR					string("Rotation")
#define SCALE_STR						string("Scale")
#define X_CSTR							"x"
#define Y_CSTR 							"y"
#define Z_CSTR 							"z"
#define BACKGROUND_COLOR_STR			string("BackgroundColor")
#define R_CSTR 							"r"
#define G_CSTR 							"g"
#define A_CSTR 							"a"
#define B_CSTR 							"b"
#define FOVY_STR 						string("fovy")
#define Z_NEAR_STR 						string("zNear")
#define Z_FAR_STR 						string("zFar")
#define VIEWPORT_STR 					string("Viewport")
#define VALUE_CSTR 						"value"
#define WIDTH_CSTR 						"width"
#define HEIGHT_CSTR 					"height"
#define PATH_CSTR 						"path"
#define SKY_BOX_STR 					string("Skybox")
#define POS_X_CSTR 						"posX"
#define NEG_X_CSTR 						"negX"
#define POS_Y_CSTR 						"posY"
#define NEG_Y_CSTR 						"negY"
#define POS_Z_CSTR 						"posZ"
#define NEG_Z_CSTR 						"negZ"
#define SHADOW_STR 						string("Shadow")
#define MAP_SIZE_CSTR 					"mapSize"
#define MATERIAL_STR 					string("Material")
#define ALBEDO_CSTR 					"diffuse"
#define NORMAL_CSTR 					"normal"
#define EMISSIVE_CSTR 					"emissive"
#define SPECULAR_CSTR 					"specular"
#define OPACITY_CSTR 					"opacity"
#define TYPE_CSTR 						"type"
#define COLOR_STR 						string("Color")
#define DIRECTIONAL_STR 				string("Directional")
#define POINT_STR						string("Point")
#define SPOT_STR 						string("Spot")
#define AMBIENT_INTENSITY_STR			string("AmbientIntensity")
#define DIFFUSE_INTENSITY_STR			string("DiffuseIntensity")
#define ATTENUATION_STR					string("Attenuation")
#define CONSTANT_CSTR					"constant"
#define LINEAR_CSTR						"linear"
#define EXP_CSTR						"exp"
#define CUTOFF_STR						string("Cutoff")
#define RIGIDBODY_STR					string("RigidBody")
#define STATIC_CSTR						"static"
#define MASS_CSTR						"mass"
#define DRAG_CSTR						"drag"
#define ANGULAR_DRAG_CSTR				"angularDrag"
#define GRAVITY_CSTR					"gravity"
#define KINEMATIC_CSTR					"kinematic"
#define COLLISION_DETECTION_CSTR		"collisionDetection"
#define CONTINUOUS_STR					string("Continuous")
#define CONTINUOUS_DYNAMIC_STR			string("Continuous Dynamic")
#define DISCRETE_STR					string("Discrete")
#define FREEZE_POSITION_STR				string("FreezePosition")
#define FREEZE_ROTATION_STR				string("FreezeRotation")
#define COLLIDERS_STR					string("Colliders")
#define PLANE_COLLIDER_STR				string("PlaneCollider")
#define BOX_COLLIDER_STR				string("BoxCollider")
#define SPHERE_COLLIDER_STR				string("SphereCollider")
#define CAPSULE_COLLIDER_STR			string("CapsuleCollider")
#define MESH_COLLIDER_STR				string("MeshCollider")
#define TERRAIN_COLLIDER_STR			string("TerrainCollider")
#define CHARACTER_CONTROLLER_STR		string("CharacterController")
#define PHYSIC_MATERIAL_STR				string("PhysicsMaterial")
#define NAME_CSTR						"name"
#define DYNAMIC_FRICTION_CSTR			"dynamicFriction"
#define STATIC_FRICTION_CSTR			"staticFriction"
#define RESTITUTION_CSTR				"restitution"
#define IS_TRIGGER_CSTR					"isTrigger"
#define DIRECTION_CSTR					"direction"
#define CENTER_CSTR						"Center"
#define SHAPE_TYPE_CSTR					"shapeType"
#define BOX_CSTR						"box"
#define UP_DIRECTION_X_CSTR				"upDirectionX"
#define UP_DIRECTION_Y_CSTR				"upDirectionY"
#define UP_DIRECTION_Z_CSTR				"upDirectionZ"
#define SLOPE_LIMIT_CSTR				"slopeLimit"
#define INVISIBLE_WALL_HEIGHT_CSTR		"invisibleWallHeight"
#define MAX_JUMP_HEIGHT_CSTR			"maxJumpHeight"
#define CONTACT_OFFSET_CSTR 			"contactOffset"
#define STEP_OFFSET_CSTR 				"stepOffset"
#define DENSITY_CSTR 					"density"
#define SCALE_COEFF_CSTR 				"scaleCoeff"
#define VOLUME_GROWTH_CSTR 				"volumeGrowth"
#define HALF_HEIGHT_CSTR 				"halfHeight"
#define HALF_SIDE_EXTENT_CSTR 			"halfSideExtent"
#define HALF_FORWARD_EXTENT_CSTR 		"halfForwardExtent"
#define RADIUS_CSTR 					"radius"
#define X_AXIS_CSTR 					"X-Axis"
#define Y_AXIS_CSTR 					"Y-Axis"
#define Z_AXIS_CSTR 					"Z-Axis"
#define CONVEX_CSTR 					"convex"
#define HEIGHT_FIELD_DATA_CSTR			"HeightFieldData"
#define HEIGHT_FIELD_FILE_CSTR			"HeightFieldFile"
#define FLAG_STR 						string("Flag")
#define CALC_TANGENT_SPACE_CSTR			"CalcTangentSpace"
#define FIND_INSTANCES_CSTR				"FindInstances"
#define FIND_INVALID_DATA_CSTR			"FindInvalidData"
#define FLIP_UV_CSTR					"FlipUVs"
#define GEN_SMOOTH_NORMALS_CSTR			"GenSmoothNormals"
#define GEN_UV_COORDS_CSTR				"GenUVCoords"
#define IMPROVE_CACHE_LOCALITY_CSTR		"ImproveCacheLocality"
#define JOIN_IDENTICAL_VERTICES_CSTR	"JoinIdenticalVertices"
#define LIMIT_BONE_WEIGHTS_CSTR			"LimitBoneWeights"
#define OPTIMIZE_MESHES_CSTR			"OptimizeMeshes"
#define OPTIMIZE_GRAPH_CSTR				"OptimizeGraph"
#define PRE_TRANSFORM_VERTICES_CSTR		"PreTransformVertices"
#define REMOVE_REDUNDANT_MATERIALS_CSTR "RemoveRedundantMaterials"
#define SPLIT_BY_BONE_COUNT_CSTR		"SplitByBoneCount"
#define TRIANGULATE_CSTR				"Triangulate"
#define TRANSFORM_UV_COORDS_CSTR		"TransformUVCoords"
#define VALIDATE_DATA_STRUCTURE_CSTR	"ValidateDataStructure"
#define MATERIALS_STR 					string("Materials")
#define SHADER_NAME_STR 				string("ShaderName")
#define MATERIAL_NAME_STR 				string("MaterialName")
#define WIREFRAME_STR					string("Wireframe")
#define OPACITY_STR 					string("Opacity")
#define BUMP_SCALING_STR 				string("BumpScaling")
#define SHININESS_STR 					string("Shininess")
#define REFLECTIVITY_STR 				string("Reflectivity")
#define REFRACTION_STR 					string("Refraction")
#define COLOR_ALBEDO_STR 				string("ColorAlbedo")
#define COLOR_AMBIENT_STR 				string("ColorAmbient")
#define COLOR_SPECULAR_STR 				string("ColorSpecular")
#define COLOR_EMISSIVE_STR 				string("ColorEmissive")
#define TC_SCALE_STR					string("TcScale")
#define TC_OFFSET_STR 					string("TcOffset")
#define TEXTURE_STR						string("Texture")
#define TARGET_CSTR 					"target"
#define MIP_MAP_CSTR 					"mipMap"
#define WRAP_S_CSTR 					"wrapS"
#define WRAP_T_CSTR 					"wrapT"
#define MAG_FILTER_CSTR 				"magFilter"
#define MIN_FILTER_CSTR 				"minFilter"
#define HDR_STR 						string("HDR")
#define EXPOSURE_CSTR 					"exposure"
#define OIT_STR 						string("OIT")
#define BLOOM_STR 						string("Bloom")
#define VR_STR 							string("VR")
#define SHADOW_TYPE_STR					string("ShadowType")
#pragma endregion
